<a href="https://colab.research.google.com/github/Stormyrider/GenAi-Intern/blob/main/Module%203/numpy_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
numbers = [1, 2, 3, 4, 5]
arr = np.array(numbers)

print(numbers)
print(arr)
print(arr.dtype)
print(arr.shape)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
int64
(5,)


In [3]:
a = np.array([1, 2, 3, 4, 5])
zeros = np.zeros(5)
ones = np.ones(5)
numbers = np.arange(1, 6)
values = np.linspace(0, 10, 5)

print(a)
print(zeros)
print(ones)
print(numbers)
print(values)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5]
[ 0.   2.5  5.   7.5 10. ]


In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[1:4])
print(arr[-1])

10
[20 30 40]
50


In [5]:
arr = np.array([10, 25, 30, 45, 50])

print(arr[arr > 30])

[45 50]


In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr * 2)
print(arr + 10)
print(arr ** 2)

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.max())
print(arr.min())

150
30.0
14.142135623730951
50
10


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [9]:
import time

numbers = list(range(1000000))

start = time.time()

result = []
for x in numbers:
    result.append(x ** 2)

python_time = time.time() - start

print("Python time:", python_time)

Python time: 0.13443636894226074


In [12]:
numbers = np.arange(1000000)

start = time.time()

result = numbers ** 2

numpy_time = time.time() - start

print("NumPy time:", numpy_time)

NumPy time: 0.0032384395599365234
